# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile para o ambiente de desenvolvimento do projeto Portfolio Astro.
#
# Requisitos:
# - Vagrant (https://www.vagrantup.com/downloads)
# - VirtualBox (https://www.virtualbox.org/wiki/Downloads)

# ENABLE EXPERIMENTAL FEATURES
ENV["VAGRANT_EXPERIMENTAL"] = "Disks"

# PLUGINS
required_plugins = ["vagrant-vmware-desktop", "vagrant-reload", "vagrant-disksize"]
required_plugins.each do |plugin|
  unless Vagrant.has_plugin?(plugin)
    system "vagrant plugin install #{plugin}"
    puts "Installed the #{plugin} plugin."
  end
end

Vagrant.configure("2") do |config|
  # Define a imagem base da VM. Debian 11 (Bullseye) é uma escolha leve e estável.
  config.vm.box = "debian/bullseye64"

  # Define um nome para a VM no VirtualBox para fácil identificação.
  config.vm.provider "virtualbox" do |vb|
    vb.name = "portfolio-dev-vm"
    vb.memory = "4096" # Aloca 4GB de RAM.
    vb.cpus = 4        # Aloca 4 CPUs.
  end

  # Configura uma rede pública (bridged) com IP estático.
  # Isso fará com que a VM apareça como um dispositivo na sua rede local,
  # permitindo o acesso pelo IP 192.168.0.132 de outros computadores/dispositivos.
  config.vm.network "public_network", ip: "192.168.0.132", bridge: [
    "eth0: Intel(R) I211 Gigabit Network Connection"
  ]

  # Redireciona a porta 4321 da VM para a porta 4321 da sua máquina local.
  # Isso permite acessar o servidor de desenvolvimento do Astro (make dev) via http://localhost:4321.
  config.vm.network "forwarded_port", guest: 4321, host: 4321, auto_correct: true
  
  # Sincroniza a pasta PAI (a raiz do projeto) para o diretório /vagrant na VM.
  # O ".." significa "um diretório acima" de onde este Vagrantfile está (a pasta /vagrant).
  # config.vm.synced_folder "..", "/vagrant", disabled: false
  config.vm.synced_folder "..", "/home/vagrant/portfolio", disabled: false
  

  # Executa o script de provisionamento que está na MESMA pasta deste Vagrantfile.
  config.vm.provision "shell", path: "setup.sh"
end