name: download-curriculum

on: [push, pull_request]

jobs:
  download_curriculum:
    name: download-curriculum
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Artefacts
        uses: actions/download-artifact@v3
        with:
          name: right-resume
          
      - name: Display structure of downloaded files
        run: ls -R
