name: Generate CV

on: [push, pull_request]

jobs:
  html_to_pdf:
    name: Generate PDF
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Convert HTML to PDF
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./index.html
          outputFile: ./right-resume.pdf
          pdfOptions: '{"margin": {"top": "1px", "left": "100px", "right": "100px", "bottom": "100px"}}'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CV PDF
          path: ./right-resume.pdf