name: Test Build Pdf

on: [push, pull_request]

jobs:
  html_to_pdf:
    name: Generate PDF
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: html to pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./example.html
          outputFile: ./example.pdf
          pdfOptions: '{"margin": {"top": "1px", "left": "100px", "right": "100px", "bottom": "100px"}}'
      - run: ls

      - name: Upload artifacts        
        uses: actions/upload-artifact@v3
        with:
          name: Example PDF
          path: ./example.pdf
      - run: ls