# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Generate Curriculum

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 1
      - name: Generate Curriculum
        uses: fifsky/html-to-pdf-action@master
        with:
            htmlFile: ./index.html
            outputFile: ./right-resume.pdf
            pdfOptions: '{"margin": {"top": "1px", "left": "100px", "right": "100px", "bottom": "100px"}}'