name: generate-curriculum

on: [push, pull_request]

jobs:
  generate_curriculum:
    name: generate-curriculum
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: HTML to PDF
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./index.html
          outputFile: ./right-resume.pdf
          pdfOptions: '{"margin": {"top": "1px", "left": "100px", "right": "100px", "bottom": "100px"}}'      

      - name: Upload artifacts        
        uses: actions/upload-artifact@v3
        with:
          name: right-resume 
          path: ./right-resume.pdf

      - name: Download Artefacts
        uses: actions/download-artifact@v3
        with:
          name: right-resume
            
      - name: Display structure of downloaded files
        run: ls -R