name: generate-curriculum

on: [push, pull_request]

jobs:
  generate_curriculum:
    name: generate-curriculum
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: HTML to PDF
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./index.html
          outputFile: ./right-resume.pdf
          #pdfOptions: '{"margin": {"top": "1px", "left": "100px", "right": "100px", "bottom": "100px"}}'      
          #pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
          pdfOptions: '{"format": "A4", "margin": {"top": "100mm", "left": "100mm", "right": "100mm", "bottom": "100mm"}}'
      - run: sudo chmod 777 right-resume.pdf
      - run: /usr/bin/git config --global user.email "marcos.silvestrini@gmail.com"
      - run: /usr/bin/git config --global user.name "marcossilvestrini"
      - run: /usr/bin/git add right-resume.pdf
      - run: /usr/bin/git commit -m "Add curriculum"
      - run: /usr/bin/git push origin main
      

      - name: Upload artifacts        
        uses: actions/upload-artifact@v3
        with:
          name: right-resume 
          path: ./right-resume.pdf

      # - name: Download Artefacts
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: right-resume
            
      # - name: Display structure of downloaded files
      #   run: sudo ls -R
